spodbtify:
  outputs:
    dev:
      type: duckdb
      path: 'spodbtify.duckdb'
      schema: 'dev'
      threads: 4

    prod:
      type: duckdb
      path: 'spodbtify.duckdb'
      schema: 'prod'
      threads: 24
  
  target: dev
